/**
 * Copyright by Calmic Sdn Bhd
 */

import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Loader2,
  Brain,
  AlertCircle,
  RefreshCw,
  FileText,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import type { Bill, BillGrokReview } from "@shared/schema";

interface GrokReviewDialogProps {
  bill: Bill & { hasPdf?: boolean };
  trigger: React.ReactNode;
}

export function GrokReviewDialog({ bill, trigger }: GrokReviewDialogProps) {
  const { toast } = useToast();
  const [open, setOpen] = useState(false);

  const { data: review, isLoading: reviewLoading } = useQuery<BillGrokReview | null>({
    queryKey: ["/api/bills", bill.id, "grok-review"],
    queryFn: async () => {
      const response = await fetch(`/api/bills/${bill.id}/grok-review`);
      if (!response.ok) {
        if (response.status === 404) return null;
        throw new Error("Failed to fetch Grok review");
      }
      return response.json();
    },
    enabled: open,
  });

  const generateMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest("POST", `/api/bills/${bill.id}/generate-grok-review`, {
        title: bill.title,
        billNumber: bill.billNumber,
      });
      if (!response.ok) {
        const error = await response.json().catch(() => ({ error: "Unknown error" }));
        throw new Error(error.error || "Failed to generate Grok review");
      }
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/bills", bill.id, "grok-review"] });
      toast({
        title: "Grok Review Generated",
        description: "Grok AI has analyzed the bill PDF and generated a comprehensive review.",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Generation Failed",
        description: error.message || "Failed to generate Grok review. Please ensure a PDF is uploaded.",
        variant: "destructive",
      });
    },
  });

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent className="max-w-4xl max-h-[85vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Brain className="w-5 h-5" />
            Grok AI Review
          </DialogTitle>
          <DialogDescription>
            Comprehensive analysis of the bill PDF by Grok AI
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="max-h-[65vh] pr-4">
          <div className="space-y-4">
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-lg flex items-center gap-2">
                  <FileText className="w-4 h-4" />
                  {bill.billNumber || "Bill"}
                </CardTitle>
                <CardDescription className="line-clamp-2">{bill.title}</CardDescription>
              </CardHeader>
            </Card>

            {reviewLoading ? (
              <div className="space-y-4">
                <Skeleton className="h-20 w-full" />
                <Skeleton className="h-32 w-full" />
                <Skeleton className="h-24 w-full" />
                <Skeleton className="h-32 w-full" />
              </div>
            ) : review ? (
              <div className="space-y-4">
                <Card>
                  <CardContent className="pt-6">
                    <div className="whitespace-pre-wrap font-mono text-sm leading-relaxed">
                      {review.review}
                    </div>
                  </CardContent>
                </Card>

                <div className="text-xs text-muted-foreground text-center pt-2">
                  Generated by Grok AI on {new Date(review.generatedAt).toLocaleDateString()} at{" "}
                  {new Date(review.generatedAt).toLocaleTimeString()}
                </div>
              </div>
            ) : (
              <Card>
                <CardContent className="py-12 text-center">
                  <AlertCircle className="w-12 h-12 mx-auto mb-4 opacity-50 text-muted-foreground" />
                  <h3 className="font-semibold text-lg mb-2">No Grok Review Yet</h3>
                  <p className="text-muted-foreground mb-4">
                    {bill.hasPdf
                      ? "Generate a comprehensive AI-powered review of this bill's PDF using Grok AI."
                      : "Please upload a PDF for this bill first before generating a Grok review."}
                  </p>
                  <Button
                    onClick={() => generateMutation.mutate()}
                    disabled={generateMutation.isPending || !bill.hasPdf}
                    data-testid={`button-generate-grok-review-${bill.id}`}
                  >
                    {generateMutation.isPending ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Analyzing PDF...
                      </>
                    ) : (
                      <>
                        <Brain className="w-4 h-4 mr-2" />
                        Generate Grok Review
                      </>
                    )}
                  </Button>
                  {!bill.hasPdf && (
                    <p className="text-sm text-muted-foreground mt-2">
                      Upload a PDF first to enable Grok review
                    </p>
                  )}
                </CardContent>
              </Card>
            )}

            {review && (
              <div className="flex justify-center">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => generateMutation.mutate()}
                  disabled={generateMutation.isPending}
                  data-testid={`button-regenerate-grok-review-${bill.id}`}
                >
                  {generateMutation.isPending ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <RefreshCw className="w-4 h-4 mr-2" />
                  )}
                  Regenerate Review
                </Button>
              </div>
            )}
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
